# Site settings
title: Shared Memory Portal
email: thomaskuntz@sharedmemory.fr
description: ""
baseurl: ""
url: "http://sharedmemory.fr"
username: "Haerezis"
fullname: "Thomas Kuntz"
qualification: "Student at the University of Strasbourg, Master 2 RISE"
qualification_url: "http://mathinfo.unistra.fr/offre-de-formation/master-mention-informatique/master-rise"
linkedin_url: "https://linkedin.com/pub/thomas-kuntz/83/979/27b"

# Build settings
markdown: kramdown
permalink: pretty

exclude: [ README.md , LICENSE , feed.xml ]
